//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenPolenov1.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPolenovEntities1 : DbContext
    {
        private static BDPolenovEntities1 _context;

        public static BDPolenovEntities1 GetContext()
        {
            if (_context == null)
                _context = new BDPolenovEntities1();
            return _context;
        }
        public BDPolenovEntities1()
            : base("name=BDPolenovEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<TovarDecoration> TovarDecoration { get; set; }
    }
}
